version: 2.1

jobs:
  build:
    machine:
      image: android:2026.05.1
    resource_class: large
    steps:
      - checkout:
          method: full
      - run:
          name: Install required Android NDK
          command: |
            yes | sdkmanager --licenses >/dev/null || true
            sdkmanager "ndk;29.0.14206865"
      - run:
          name: Initialize Monero submodule
          command: |
            git config -f .gitmodules submodule.external-libs/monero.url https://gitea.com/anonero/monero.git
            git submodule sync --recursive
            git submodule update --init --recursive
      - run:
          name: Build native libraries
          command: |
            cd external-libs
            make android NPROC=2
      - run:
          name: Build APK
          command: |
            chmod +x ./gradlew
            ./gradlew assembleAnonRelease --no-daemon
      - store_artifacts:
          path: app/build/outputs/apk/anon/release
          destination: apk

workflows:
  build:
    jobs:
      - build
